services:
  payment:
    build: ./payment/
    ports:
      - "5001:5001"
   #  extra_hosts:
     #  - "host.docker.internal:192.168.1.6"

  webapp:
    build: ./main/
    ports:
      - "5000:5000"
    depends_on:
      - payment
    # extra_hosts:
     #  - "host.docker.internal:192.168.1.6"
